AllCops:
  TargetRubyVersion: 3.3
@@ -12,8 +13,6 @@ AllCops:
  - Taps/*/*/vendor/**/*
  SuggestExtensions:
    rubocop-minitest: false
Homebrew:
  Enabled: true
Layout/ArgumentAlignment:
  Exclude:
  - Taps/*/*/*.rb