- Homebrew/bin/*
  - Homebrew/vendor/**/*
  - Taps/*/*/vendor/**/*
  - "**/vendor/**/*"
  SuggestExtensions:
    rubocop-minitest: false
Layout/ArgumentAlignment:
Style/OptionalBooleanParameter:
  AllowedMethods:
  - respond_to?
  - respond_to_missing?
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/ReturnNil: