include:
          - container: debian7
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --tag ${{matrix.container}} .
@@ -41,7 +41,7 @@ jobs:
        run: docker cp ${{github.sha}}:/home/linuxbrew/bootstrap-binaries .

      - name: Upload binaries to GitHub Actions
        uses: actions/upload-artifact@v3
        uses: actions/upload-artifact@v4
        with:
          name: Bootstrap binaries
          name: bootstrap-${{matrix.binary}}
          path: bootstrap-binaries
  7 changes: 4 additions & 3 deletions7  
.github/workflows/release.yml
Original file line number	Diff line number	Diff line change
@@ -20,13 +20,14 @@ jobs:
      GH_TOKEN: ${{github.token}}
      TAG: ${{github.event.inputs.tag}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v4

      - name: Download binaries from GitHub Actions
        uses: actions/download-artifact@v3
        uses: actions/download-artifact@v4
        with:
          name: Bootstrap binaries
          pattern: bootstrap-*
          path: bootstrap-binaries
          merge-multiple: true

      - name: Push tag
        run: gh release create "$TAG" --generate-notes