 ignore:
      - dependency-name: actions/stale
      - dependency-name: dessant/lock-threads
    groups:
      artifacts:
        patterns:
          - actions/*-artifact

  - package-ecosystem: bundler
    directory: /